apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
port: 20021
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
kindV1Alpha4Cluster:
  name: goldpinger-test
  nodes:
  - role: control-plane
  - role: worker
  - role: worker
  networking:
    apiServerPort: 30022
